# Generated by Django 3.2.7 on 2021-11-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camname', models.CharField(default='cam', max_length=50)),
                ('note', models.TextField(max_length=200)),
                ('url', models.CharField(max_length=100)),
                ('online', models.BooleanField(default=False)),
                ('errormsg', models.CharField(max_length=50)),
            ],
        ),
    ]
