# Generated by Django 3.2.6 on 2021-11-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cams',
            name='errormsg',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
